### ISSUE TITLE
Support reading Apple ID username/email from environment

### ISSUE THREAD

**Issue by maxfierke** [mitchellh/gon#9]
Right now the properties within `apple_id` are being passed verbatim to `altool`, which has native support for reading Apple ID password from the environment (or keychain), but it would handy to also support providing the Apple ID username via an environment variable.

I'd like to commit my application's `gon` config to the repo that uses it, but would prefer to avoid publishing my Apple ID username/email.

If this seems reasonable, I can throw up a PR.

**Comment by mitchellh** [comment]
Hey, I think that is reasonable. As you probably already know: the syntax we use for the Apple ID password is just what `altool` accepts so we can’t really accept the same values for the username (since I don’t believe `altool` parses those for keychain or env access).

If I recall in Apple’s docs they use the AC_USERNAME and AC_PASSWORD env vars. I’d be supportive of just supporting those as defaults if there is no config set.
